### ISSUE TITLE
Tiles are not styled properly at Leaflet 1.0.1

### ISSUE THREAD

**Issue by haoliangyu** [IvanSanchez/Leaflet.VectorGrid#14] opened 2016-10-03 04:09 UTC
After upgrading Leaflet from 1.0.0 to 1.0.1, all tiles on the map become transparent, even though they are created without error.

**Comment by IvanSanchez** [comment] 2016-10-03 07:18
1.0.1 works fine for me.

Closing due to not being reproducible.

**Closed by IvanSanchez** 2016-10-03 07:18 UTC
